spring:
  application:
    name: iam-service
  
  # Configuração do Banco de Dados (Conectando no nosso Docker)
  datasource:
    url: jdbc:postgresql://localhost:5432/locadora_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  # Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update  # Cria/atualiza tabelas automaticamente (usaremos 'validate' em produção)
    show-sql: true      # Mostra os comandos SQL no console (ótimo para aprender)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Configuração do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

# Configuração do Servidor (Porta onde o serviço vai rodar)
server:
  port: 8081